# Site Settings

title: 'increasing entropy'

# The slogan describes your website and is used on homepage in <title> and other important places
slogan: 'Formally Informal'

# The description is used on homepage and in the footer to quickly describe your website. Use a maximum of 150 characters for SEO-purposes.

description: 'Informal blog of John Paul Mattia'

# Main author of the website
# See > authors.yml
author: jpmattia

# This URL is the main address for absolute links. Don't include a slash at the end.
#
# url: 'https://jpmattia.github.io'
# baseurl: ''

# This URL points directly to the images directory making
# things easier to link to images in posts and templates. It needs a slash at the end.
#
# Example: <img src="{{ site.urlimg }}{{ post.image.title }}" />
# Markdown-Example for posts ![Image Text]({{ site.urlimg }}image.jpg)
#
urlimg: '/images/'


# Logo size is 600x80 pixels
logo: "logo.png"

# Plugins
plugins:
    - jekyll-asciidoc
    - jekyll-gist
    - jekyll-paginate


# Pagination
paginate: 5                      # Paginates all X entries
paginate_path: "blog/page:num"   # Pagination path › Important for blog page in /blog/ to work


# Theme works best with Kramdown (using the table of contents function)
markdown           : kramdown
permalink          : /:categories/:title/
highlight          : rouge
excerpt_separator  : "<!--more-->"
include            : ['.htaccess']
# Exclude these files from your production _site
exclude:
    - .sass-cache
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - INSTALL.md
    - vendor


# The language setting is used in /includes/header.html for html-settings
language: 'en'


# Used › default.html front-matter and compress.html
# Options › http://jch.penibelst.de
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  profile: false
  ignore:
    envs: [development]


# Default Settings

defaults:
  -
    scope:
      path: '' 				# an empty string here means all files in the project
      type: 'pages'
    values:
      show_meta: false 	# Hide metadata for all pages
      # sidebar:    		# Possible values › left, right › by default there will be no sidebar
      comments: false
      author: jpmattia     # Default author for pages
  -
    scope:
      path: ''
      type: 'posts'
    values:
      show_meta: true   # Show metadata for all posts
      # sidebar:        # Possible values › left, right › by default there will be no sidebar
      comments: false
      author: phlow     # Default author for posts



# Navication
#  Open _data/navigation.yml to adjust the left and right topbar navigation


# SEO
# google_site_verification        : 'Vk0IOJ2jwG_qEoG7fuEXYqv0m2rLa8P778Fi_GrsgEQ'
# bing_webmastertools_id          : '0FB4C028ABCF07C908C54386ABD2D97F'
# yandex_site_verification      : ''
# alexa_verify_id               : ''



# Favicons
# More information » https://mathiasbynens.be/notes/touch-icons

favicon-32x32                        : 'favicon-32x32.png'
# touch-icon-192x192                   : 'touch-icon-192x192.png'
apple-touch-icon-180x180-precomposed : 'apple-touch-icon.png'
# apple-touch-icon-152x152-precomposed : 'apple-touch-icon-152x152-precomposed.png'
# apple-touch-icon-144x144-precomposed : 'apple-touch-icon-144x144-precomposed.png'
# apple-touch-icon-120x120-precomposed : 'apple-touch-icon-120x120-precomposed.png'
# apple-touch-icon-114x114-precomposed : 'apple-touch-icon-114x114-precomposed.png'
# apple-touch-icon-76x76-precomposed   : 'apple-touch-icon-76x76-precomposed.png'
# apple-touch-icon-72x72-precomposed   : 'apple-touch-icon-72x72-precomposed.png'
apple-touch-icon-precomposed         : 'apple-touch-icon.png'
# msapplication_tileimage              : 'msapplication_tileimage.png'               # Size 144x144
# msapplication_tilecolor              : '#fabb00'


# Facebook-Optimization › http://j.mp/fb_optimize
# og_image                             : 'http://images.phlow.de/phlow/phlow_de-logo-512x.png'
# og_locale                            : 'en_EN'
# og_type                              : 'website'


# Social media
#  Open _data/socialmedia.yml to adjust the left and right topbar navigation


socialmedia:
    twitter   : jpmattia
    facebook  : jpmattia


# disqus
# used in _includes/comments
# disqus_shortname: 


# More › http://sass-lang.com/
# More › http://jekyllrb.com/docs/assets/#sassscss

sass:
    sass_dir : _sass
    style    : :compressed

# Google analytics
# used in _includes/footer_scripts
# google_analytics_tracking_id:



#  tawk.to is a free live chat app that lets you monitor and chat
#  with visitors on your website or from a free customizable page
#
#  To load the script add tawkto: true in front matter of each page
#
# used in _includes/footer_scripts

# tawkto_embed_uri:


#  Asciidoctor is a fast text processor and publishing toolchain for converting
#  AsciiDoc content to HTML5, DocBook 5 (or 4.5) and other formats.
#
#  https://github.com/asciidoctor/jekyll-asciidoc
#  https://github.com/asciidoctor

asciidoctor-enabled: false
asciidoctor:
  description: 
  attributes:
    source-highlighter: coderay
    coderay-css: style
    icons: font
